
kind: Namespace
apiVersion: v1
metadata:
  name: mhero
  labels:
    name: mhero
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mhero-deployment
  namespace: mhero
  labels:
    app: mhero
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mhero
  template:
    metadata:
      labels:
        app: mhero
    spec:
      nodeSelector:
        purpose: general
      containers:
      - name: mhero
        image: charlie83gs/react_page:latest
        ports:
        - containerPort: 3000
      
---
apiVersion: v1
kind: Service
metadata:
  name: mhero-service
  namespace: mhero
spec:
  selector:
    app: mhero
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mhero
  namespace: mhero
spec:
  hosts:
  - "*"
  gateways:
  - istio-custom/devops-gateway
  http:
    - name: "mhero-routes"
      match:
      - uri: 
          prefix: "/mhero"
      route:
        - destination:
            host: mhero-service.mhero.svc.cluster.local

